sudo: required

language: python

python: 3.6

install:
  - pip install pipenv
  - pipenv install --dev --system --skip-lock

script:
  - pytest


notifications:
  email:
    on_success: change
    on_failure: always